In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

# 실행할 때마다 같은 결과를 출력하기 위해 설정하는 부분입니다.
np.random.seed(3)
tf.random.set_seed(3)

## 1. 데이터 읽어오기

In [10]:
# 데이터프레임으로 읽어오기
import pandas as pd
df = pd.read_csv("iris.csv", header = None)
df = df.values

In [11]:
df.shape

(150, 5)

In [12]:
df

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

## 2. 데이터 전처리

In [13]:
X = df[:, 0:4].astype(float)
Y = df[:, 4]
print(X.shape)
print(Y.shape)

# 문자열을 숫자로 변환 (원핫 인코딩)
e = LabelEncoder()
e.fit(Y)
Y = e.transform(Y)
Y_encoded = tf.keras.utils.to_categorical(Y)
print(Y_encoded)
print(Y_encoded.shape)

(150, 4)
(150,)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]


## 3. 모델 설계

In [17]:
model = Sequential()

model.add(Dense(20, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))

## 4. 모델 컴파일

In [18]:
# 딥러닝을 실행합니다.
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

## 5. 학습

In [19]:
# epoch = 100: 샘플이 처음부터 끝까지 200번 재사용될 때까지 실행을 반복
# batch_size = 10: 전체 샘플을 10개씩 끊어서 집어넣기
model.fit(X, Y_encoded, epochs=200, batch_size=10)

Epoch 1/200
15/15 [==============================] - 0s 2ms/step - loss: 1.2607 - accuracy: 0.3333
Epoch 2/200
15/15 [==============================] - 0s 967us/step - loss: 1.0769 - accuracy: 0.3333
Epoch 3/200
15/15 [==============================] - 0s 750us/step - loss: 0.9789 - accuracy: 0.3333
Epoch 4/200
15/15 [==============================] - 0s 2ms/step - loss: 0.9296 - accuracy: 0.3400
Epoch 5/200
15/15 [==============================] - 0s 2ms/step - loss: 0.8869 - accuracy: 0.5600
Epoch 6/200
15/15 [==============================] - 0s 1ms/step - loss: 0.8514 - accuracy: 0.6733
Epoch 7/200
15/15 [==============================] - 0s 2ms/step - loss: 0.8170 - accuracy: 0.7000
Epoch 8/200
15/15 [==============================] - 0s 898us/step - loss: 0.7752 - accuracy: 0.6867
Epoch 9/200
15/15 [==============================] - 0s 888us/step - loss: 0.7403 - accuracy: 0.6667
Epoch 10/200
15/15 [==============================] - 0s 2ms/step - loss: 0.7025 - accuracy: 0.6800
E

15/15 [==============================] - 0s 1ms/step - loss: 0.0700 - accuracy: 0.9800
Epoch 164/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0725 - accuracy: 0.9733
Epoch 165/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0714 - accuracy: 0.9800
Epoch 166/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0712 - accuracy: 0.9800
Epoch 167/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0786 - accuracy: 0.9800
Epoch 168/200
15/15 [==============================] - 0s 783us/step - loss: 0.0751 - accuracy: 0.9733
Epoch 169/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0703 - accuracy: 0.9800
Epoch 170/200
15/15 [==============================] - 0s 845us/step - loss: 0.0693 - accuracy: 0.9800
Epoch 171/200
15/15 [==============================] - 0s 329us/step - loss: 0.0678 - accuracy: 0.9800
Epoch 172/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0693 - accuracy: 0.980

In [21]:
model.evaluate(X, Y_encoded)[1]

5/5 [==============================] - 0s 0s/step - loss: 0.0630 - accuracy: 0.9867


0.9866666793823242